# Cloudflare Workers Configuration
# Documentation: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "fieldforce-crm-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Cloudflare Account
# ⚠️ TODO: Update with correct account ID from Cloudflare Dashboard
# Get from: https://dash.cloudflare.com -> Workers & Pages -> Overview (right sidebar)
account_id = "610762493d34333f1a6d72a037b345cf"  # VERIFY THIS VALUE

# Environment Variables (public only)
[vars]
ENVIRONMENT = "production"
JWT_EXPIRES_IN = "15m"
API_VERSION = "v1"
EMAIL_FROM = "noreply@fieldforce.com"
AWS_SES_SMTP_HOST = "email-smtp.ap-south-1.amazonaws.com"
AWS_SES_SMTP_PORT = "587"

# ⚠️ SECRETS - Set via: echo "value" | wrangler secret put SECRET_NAME
# DATABASE_URL - Neon PostgreSQL connection string
# JWT_SECRET - Strong random secret for JWT signing
# AWS_SES_SMTP_USER - AWS SES SMTP username
# AWS_SES_SMTP_PASSWORD - AWS SES SMTP password

# Cloudflare KV Namespace (Cache - FREE tier available)
[[kv_namespaces]]
binding = "KV"
id = "07ea4a2def1d4fd1826f37551207ad46"

# Cloudflare R2 Bucket (Storage - FREE: 10GB/month)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fieldforce-crm-storage"

# Note: Cloudflare Queues require PAID Workers plan
# For free tier, use Durable Objects or process jobs immediately

# Node.js compatibility for Prisma
node_compat = true

# Development server configuration
[dev]
port = 8787  # Fixed port for development server

# Development environment
[env.dev]
name = "fieldforce-crm-api-dev"
vars = { ENVIRONMENT = "development", EMAIL_FROM = "dev@fieldforce.com" }
kv_namespaces = [{ binding = "KV", id = "YOUR_DEV_KV_NAMESPACE_ID" }]
r2_buckets = [{ binding = "BUCKET", bucket_name = "fieldforce-crm-storage-dev" }]
